Adding new spiders
Ahmad34201/web_scraping pull request #1
Opened 2023-09-26 11:10 UTC by Ahmad34201

Adding new spider's

2023-09-26 11:18 UTC, Ahmad34201 commented
@faisal05sa
@umer-nadeem

review PR

2023-09-27 08:31 UTC, umer-nadeem requested changes

2023-09-27 08:31 UTC, umer-nadeem commented on Spiders/spiders_practice/spiders_practice/spiders/ackermans_co.py
> +import json
Imports should be grouped in the following order:

Standard library imports.
Related third party imports.
Local application/library specific imports.

2023-09-27 08:31 UTC, umer-nadeem commented on Spiders/spiders_practice/spiders_practice/spiders/ackermans_co.py
> +
For levels you using the same code, i think we can move this to de__make_navigation_request function to remove code redundancy

2023-09-27 08:31 UTC, umer-nadeem commented on Spiders/spiders_practice/spiders_practice/spiders/ackermans_co.py
> +            l1_cat = json_data.get('categories', [])[0]
Use name like level1_cat or label1 instead of l1

2023-09-27 08:31 UTC, umer-nadeem commented on Spiders/spiders_practice/spiders_practice/spiders/ackermans_co.py
> +            return 0
we can use 

return 1 if status == "IN_STOCK" else 0 instead of if else

2023-09-27 08:31 UTC, umer-nadeem commented on Spiders/spiders_practice/spiders_practice/spiders/ackermans_co.py
> +        return images
Use list comprehension here

2023-09-27 13:16 UTC, umer-nadeem requested changes

2023-09-27 13:16 UTC, umer-nadeem commented on Spiders/spiders_practice/spiders_practice/spiders/ackermans_co.py
> +from ..utils import *
This should be the order

import json
from copy import deepcopy

from scrapy import Request
from scrapy.loader import ItemLoader

from ..items import ProductItem, SizeItem, PriceItem, ProductLoader
from ..utils import *

2023-09-27 13:16 UTC, umer-nadeem commented on Spiders/spiders_practice/spiders_practice/spiders/ackermans_co.py
> +                        level2_cat_url = f"{level1_cat_url}/{cat2.get('url_key', '')}"
we can use cat1.get('children', []) and remove the if statement

2023-09-27 13:39 UTC, Ahmad34201 commented on Spiders/spiders_practice/spiders_practice/spiders/ackermans_co.py
> +from ..utils import *
already resolved it

2023-09-28 09:52 UTC, faisal05sa requested changes

2023-09-28 09:52 UTC, faisal05sa commented on Spiders/spiders_practice/spiders_practice/items.py
> +    def create(cls, response, id, url, categories):
We don't need such functions with Item classes. They are available by default. 
item = ProductItem(field_1="value1", ...)
However, if you want to extract some values from response, you can create a function in utils.

2023-09-28 09:52 UTC, faisal05sa commented on Spiders/spiders_practice/spiders_practice/spiders/ackermans_co.py
> +        return item['name']
We should not create these one-line functions to get some values from a dict.

2023-10-02 10:53 UTC, closed without merging